$schema: ./config.schema.json

# Start the server on 8001 and bind to loopback interface only (so it's inaccessible from outside)
server:
  host: 127.0.0.1
  port: 8001

# Persistent store in a database, with 7-day retention of old events
database:
  retention_days: 7
  db_path: ./data/database.db

# Poll gmail events and publish them (needs token setup through CLI).
# See docs for more sources, and configuration options.
sources:
  gmail:
    token_file: ./data/google_token.json
    poll_interval: "1m"
    exclude_label_ids: [ "SPAM", "DRAFT" ]
  google_drive:
    token_file: "data/google_token.json"
    poll_interval: "1m"
    bootstrap_mode: "baseline_only"
    coalesce:
      - match: [ "google.drive.file_updated", "google.drive.file_moved" ]
        strategy: "debounce"
        window: "10m"
  google_calendar:
    token_file: "data/google_token.json"
    poll_interval: "1m"
    calendar_ids:
      - "john.doe@gmail.com"
      - "shared-calendar-id@group.calendar.google.com"
    calendar_overrides:
      "shared-calendar-id@group.calendar.google.com":
        max_into_future: "7d" # don't report forever repeating events from work calendar
  # add more sources according to docs

# Publish SSE stream of events.
# See docs for more sinks, and configuration options.
sink:
  sse: {}
  # add more sinks according to docs